studentwebsite/books/urls.py
from django.urls import path, reverse_lazy
from . import views

#===========================================================================

#===========================================================================
app_name='books'
urlpatterns = [
    path('', views.BookListView.as_view(),name='all'),   #for home page rendering
   #path('books', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('book/create',
        views.BookCreateView.as_view(success_url=reverse_lazy('books:all')), name='book_create'),
    path('book/<int:pk>/update',
        views.BookUpdateView.as_view(success_url=reverse_lazy('books:all')), name='book_update'),
    path('book/<int:pk>/delete',
        views.BookDeleteView.as_view(success_url=reverse_lazy('books:all')), name='book_delete'),
    path('book_image/<int:pk>', views.stream_file, name='book_image'),
    path('book/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='book_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('books')), name='book_comment_delete'),
    path('book/<int:pk>/favorite',
    views.AddFavoriteView.as_view(), name='book_favorite'),
    path('book/<int:pk>/unfavorite',
    views.DeleteFavoriteView.as_view(), name='book_unfavorite'),
    #================================================================
    path('fav', views.BookFavView.as_view(),name='fav'),
]

studentwebsite/payingguest/urls.py
from django.urls import path, reverse_lazy
from . import views

#===========================================================================

#===========================================================================
app_name='payingguest'
urlpatterns = [
    path('', views.PayingguestListView.as_view(),name='all'),   #for home page rendering
   #path('payingguests', views.PayingguestListView.as_view(), name='payingguests'),
    path('payingguest/<int:pk>', views.PayingguestDetailView.as_view(), name='payingguest_detail'),
    path('payingguest/create',
        views.PayingguestCreateView.as_view(success_url=reverse_lazy('payingguest:all')), name='payingguest_create'),
    path('payingguest/<int:pk>/update',
        views.PayingguestUpdateView.as_view(success_url=reverse_lazy('payingguest:all')), name='payingguest_update'),
    path('payingguest/<int:pk>/delete',
        views.PayingguestDeleteView.as_view(success_url=reverse_lazy('payingguest:all')), name='payingguest_delete'),
    path('payingguest_image/<int:pk>', views.stream_file, name='payingguest_image'),
    path('payingguest/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='payingguest_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('payingguest_detail')), name='payingguest_comment_delete'),
    path('payingguest/<int:pk>/favorite',
    views.AddFavoriteView.as_view(), name='payingguest_favorite'),
    path('payingguest/<int:pk>/unfavorite',
    views.DeleteFavoriteView.as_view(), name='payingguest_unfavorite'),
    #================================================================
    path('fav', views.PayingguestFavView.as_view(),name='fav'),
]

studentwebsite/studentwebsite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

from books import views

admin.site.site_header = "Book A Room Admin"
admin.site.site_title = "Book A Room Admin Portal"
admin.site.index_title = "Welcome to Book A Room Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('books/', include('books.urls')),
    path('cart/', include('carts.urls')),
    path('payingguest/', include('payingguest.urls')),
    #path('fav/', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    url(r'^signup/$',views.signup, name='signup'),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]
#===============================================================
# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

studentwebsite/payingguest/forms.py
from django import forms
from payingguest.models import Payingguest
from django.core.files.uploadedfile import InMemoryUploadedFile
from payingguest.humanize import naturalsize

#=====================================
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# Create the form class.
class PGCreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    image = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'image'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Payingguest
        fields = ['City', 'rent','user_address','pg_address', 'condition','image']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('image')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('image', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(PGCreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.image   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.image = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

class PGCommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)
# https://docs.djangoproject.com/en/3.0/toads/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
class PGSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

studentwebsite/payingguest/views.py
from django.shortcuts import render,redirect

from payingguest.models import Payingguest,PGFav
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile

from payingguest.owner import OwnerListView, OwnerDetailView,OwnerDeleteView
from django.urls import reverse
from payingguest.forms import PGCreateForm
from payingguest.forms import PGCommentForm
from payingguest.models import PGComment

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

from payingguest.utils import dump_queries
from django.db.models import Q
from django.contrib.humanize.templatetags.humanize import naturaltime

#
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from payingguest.forms import PGSignUpForm
# Create your views here.
from django.contrib import messages

class PayingguestListView(OwnerListView):
    model = Payingguest
    # By convention:
    # template_name = "myarts/article_list.html"
    template_name = "payingguest/payingguest_list.html"
    #
    def get(self, request) :
        payingguest_list = Payingguest.objects.all()
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_payingguest.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        #weeeeeeeeellllllllllllllll
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Ad.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(City__contains=strval)
            query.add(Q(condition__contains=strval), Q.OR)
            objects = Payingguest.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :
            # try both versions with > 4 Ads and watch the queries that happen
            objects = Payingguest.objects.all().order_by('-updated_at')[:10]

            # objects = Ad.objects.select_related().all().order_by('-updated_at')[:10]

        # Augment the Ad_list
        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)
        #weeeeeeelllllllllllll(chech here)
        ctx = {'payingguest_list' : objects, 'favorites': favorites,'search': strval}
        retval = render(request, self.template_name, ctx)
        dump_queries()
        return retval;
    #


class PayingguestDetailView(OwnerDetailView):
    model = Payingguest
    template_name = "payingguest/payingguest_detail.html"
    def get(self, request, pk) :
        x = Payingguest.objects.get(id=pk)
        comments = PGComment.objects.filter(payingguest=x).order_by('-updated_at')
        comment_form = PGCommentForm()
        context = { 'payingguest' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class PayingguestCreateView(LoginRequiredMixin, View):
    template_name = 'payingguest/payingguest_form.html'
    success_url = reverse_lazy('payingguest:all')

    def get(self, request, pk=None):
        form = PGCreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = PGCreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        return redirect(self.success_url)


class PayingguestUpdateView(LoginRequiredMixin, View):
    template_name = 'payingguest/payingguest_form.html'
    success_url = reverse_lazy('payingguest:all')

    def get(self, request, pk):
        pic = get_object_or_404(Payingguest, id=pk, owner=self.request.user)
        form = PGCreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Payingguest, id=pk, owner=self.request.user)
        form = PGCreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()

        return redirect(self.success_url)


class PayingguestDeleteView(OwnerDeleteView):
    model = Payingguest
    template_name = "payingguest/payingguest_confirm_delete.html"

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Payingguest, id=pk)
        comment = PGComment(text=request.POST['comment'], owner=request.user, payingguest=f)
        comment.save()
        return redirect(reverse('payingguest:payingguest_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = PGComment
    template_name = "payingguest/payingguest_comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        payingguest = self.object.payingguest
        return reverse('payingguest:payingguest_detail', args=[payingguest.id])

def stream_file(request, pk):
    pic = get_object_or_404(Payingguest, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.image)
    response.write(pic.image)
    return response

#=================================================================
def signup(request):
    if request.method == 'POST':
        form = PGSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, 'Account created Succesfully Welcome!')
            return redirect('/payingguest')
    else:
        form = PGSignUpForm()
    return render(request, 'registration/signup.html', {'form': form})
#=================================================================

#for favorite:

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Payingguest, id=pk)
        fav = PGFav(user=request.user, payingguest=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

class PayingguestFavView(OwnerListView):
    model = Payingguest
    template_name = "payingguest/payingguest_favorite.html"
    #=========================================

    def get(self, request) :
        payingguest_list = Payingguest.objects.all()
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_payingguest.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        #weeeeeeeeellllllllllllllll
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Ad.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(City__contains=strval)
            query.add(Q(condition__contains=strval), Q.OR)
            objects = Payingguest.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :
            # try both versions with > 4 Ads and watch the queries that happen
            objects = Payingguest.objects.all().order_by('-updated_at')[:10]

            # objects = Ad.objects.select_related().all().order_by('-updated_at')[:10]

        # Augment the Ad_list
        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)
        #weeeeeeelllllllllllll(chech here)
        ctx = {'payingguest_list' : objects, 'favorites': favorites,'search': strval}
        retval = render(request, self.template_name, ctx)
        dump_queries()
        return retval

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Payingguest, id=pk)
        try:
            fav = PGFav.objects.get(user=request.user, payingguest=t).delete()
        except PGFav.DoesNotExist as e:
            pass

        return HttpResponse()

studentwebsite/payingguest/templates/payingguest/payingguest_detail.html
{% extends "base_bootstrap.html" %}
{% load static %}
{% load humanize %}
{% block title %}Services | PG
{% endblock title %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.75); /*dim the background*/
}
</style>
{% endblock %}
<!--======================================-->
{% block navbar %}
{% load app_tags %}
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky">
<a class="navbar-brand" href=""><i class="fas fa-book-reader" style="font-size:200%;"></i></a>

  <!--<div class="container-fluid">-->
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <!--<ul class="nav navbar-nav">
      {% url 'books' as books %}
      <li {% if request.get_full_path == books %}class="active"{% endif %}>
          <a href="{% url 'books:all' %}">Books</a></li>
    </ul>-->
    <!--======================================================================================-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About Us</a>
            </li>
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="/services" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Services
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/books">Second hand books</a>
                <a class="dropdown-item" href="/payingguest">Find PG</a>
              </div>
            </li>
            <li class="nav-item" >
                <a class="nav-link" href="/contact">Contact Us</a>
              </li>
         </ul>
         <hr style="border: 5px solid white;">
    <!--======================================================================================-->
    <ul class="nav navbar-nav navbar-right loginbutton">
        {% if user.is_authenticated %}
        <li style="margin-top:5px;">
        <a href="{% url 'payingguest:payingguest_create' %}" style="color:white;">Add PG</a>
        </li>
        <li style="margin-top:5px;">
        <a href="/payingguest/fav" style="color:white;">Fav PG</a>
        </li>
        
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle" style="color:white;">
                <img class="gravatar" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'payingguest:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'payingguest:all' %}" style="color:white;">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
</header>
{% endblock %}
<!--======================================-->
{% block content %}
<div class="container detailpage">
{% if payingguest.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="" class="detailimgpg" src="{% url 'payingguest:payingguest_image' payingguest.id %}">
</div>
{% endif %}
{% if payingguest.content_type %}
<div class="detailpageimgdivpg">
<img class="detailpageimgpg" src="{% url 'payingguest:payingguest_image' payingguest.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
    <p class="zoomtext" style="">(Click/Tap to zoom.)
    {% if payingguest.owner == user %}
    <a href="{% url 'payingguest:payingguest_update' payingguest.id %}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'payingguest:payingguest_delete' payingguest.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
    
    </p>
    </div>
{% endif %}
<hr>
<div class="bookdetails"style="">
<h1>City: {{ payingguest.City }}</h1>
<p style="font-size:150%;">
   <b>Rent(&#x20B9;):</b> {{ payingguest.rent }}
</p>
<p style="font-size:125%;">
<b>Condition: </b>{{ payingguest.condition }}
</p>
<p style="font-size:125%;">
<b>Owner Address: </b>{{ payingguest.user_address }}
</p>
<p style="font-size:125%;">
<b>PG Address: </b>{{ payingguest.pg_address }}
</p>

<p>
<b>Uploaded: </b>({{ payingguest.updated_at|naturaltime }})
</p>
<p>
<b>Uploaded by: </b>{{ payingguest.owner}}
</p>
</div>

{% if user.is_authenticated %}
<br clear="all"/>

<p>
<div class="commentbox">
{% load crispy_forms_tags %}
<form method="post" action="{% url 'payingguest:payingguest_comment_create' payingguest.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
</form>
</p>
{% endif %}
<div class="commentbox">
{% for comment in comments %}
<p style="font-size:110%;"> <b>{{comment.owner}}: </b>{{ comment.text }}
<p style="font-size:85%;">({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'payingguest:payingguest_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a></p>
{% endif %}

</p>
{% endfor %}

<p>
<a style="color: blue;" href="{% url 'payingguest:all' %}"> &larr; Back to PG list</a>
</p>
</div>
</div>
</div>
{% endblock %}

studentwebsite/payingguest/templates/payingguest/payingguest_list.html
{% extends "base_menu.html" %}
{% load static %}
{% block content %}
<!--<div class="container-fluid px-0">
    <img src="{% static "website/contact.jpg" %}" class="d-block w-100" alt="...">
</div>-->
<!-------------------------------------------------------------------------------->
<!--<div class="content">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static "website/book1.jpg" %}" class="d-block w-100 bannerbook" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static "website/book2.jpg" %}" class="d-block w-100 bannerbook" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static "website/book3.jpg" %}" class="d-block w-100 bannerbook" alt="...">
      </div>
    </div>
    </div>-->
    <!--<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>-->
  
  <!--<br>
  <h1 style="text-align:center;">Welcome to our Book Store</h1>-->
  <div class="searchbar" style="box-shadow: 0 12px 16px 0 rgba(0,0,0,0.5);">
  <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
  <form style="text-align:center;">
    <input type="text" placeholder="Search.." name="search"
    {% if search %} value="{{ search }}" {% endif %}
    >
    <button type="submit"><i class="fa fa-search"></i></button>
  <a href="{% url 'payingguest:all' %}"><i class="fa fa-undo" style="color:white;"></i></a>
  </form>
  <a class="button"  href="{% url 'payingguest:payingguest_create' %}">Add PG</a>
  </div>
  <p>
  {% if payingguest_list %}
  <div class = "row" style="width:100%;">
    {% for payingguest in payingguest_list %}
      <div class="col-sm-9 col-md-6 col-lg-3 img-thumbnail bookdiv">
      <!--========================================================-->
      {% if user.is_authenticated %}
          <button style="" class="heart">
          <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
          <a href="#" onclick=
              "favPost('{% url 'payingguest:payingguest_unfavorite' payingguest.id %}', {{ payingguest.id }} );return false;"
              {% if payingguest.id not in favorites %} style="display: none;" {% endif %}
              id="favorite_star_{{payingguest.id}}">
          <span class="fa-stack" style="vertical-align: middle;color: red;">
          <i class="fa fa-heart fa-stack-2x" style="color: red;"></i>
          <i class="fa fa-heart-o fa-stack-2x " ></i>
          </span>
          </a>
          <!-- the second href -->
          <a href="#" onclick=
              "favPost('{% url 'payingguest:payingguest_favorite' payingguest.id %}', {{ payingguest.id }} );return false;"
              {% if payingguest.id in favorites %} style="display: none;" {% endif %}
              id="unfavorite_star_{{payingguest.id}}">
          <span class="fa-stack" style="vertical-align: middle;">
          <i class="fa fa-heart fa-stack-2x" style="display: none; color: red;"></i>
          <i class="fa fa-heart-o fa-stack-2x"></i>
          </span>
          </a>
          </button>
          {% endif %}
      <!--========================================================-->
      <div class="containpg">
      <a href="{% url 'payingguest:payingguest_detail'  payingguest.id %}">
        <img  class="imgphonepg" src="{% url 'payingguest:payingguest_image' payingguest.id %}"></a>
        <a href="{% url 'payingguest:payingguest_detail'  payingguest.id %}">
        <div class="middlepg">
            <div class="text">PG Details</div>
        </div></a>
      </div>
      <div style="" class="imagephone">
      <a style="color:black;font-size:125%;" href="{% url 'payingguest:payingguest_detail'  payingguest.id %}">City: <b>{{ payingguest.City }}</b></a>
      <div>
      <b>Rent(&#x20B9;): </b>{{ payingguest.rent }}
      </div>
      </div>
          {% if payingguest.owner == user %}
          <div>
          <a href="{% url 'payingguest:payingguest_update' payingguest.id %}">(Edit |</a>
          <a href="{% url 'payingguest:payingguest_delete' payingguest.id %}">Delete)</a></div>
          {% endif %}
          <div>
          <b>PG Condition: </b>
              {% if payingguest.condition|length < 100 %}
                  {{ payingguest.condition }}
              {% else %}
                  {{ payingguest.condition|slice:"0:99" }}
                  <a href="{% url 'payingguest:payingguest_detail'  payingguest.id %}">...</a>
              {% endif %}
          </div>
          <small>
          {% if payingguest.owner.username %}
              posted by {{ payingguest.owner.username }}
          {% endif %}
          {{ payingguest.natural_updated }}
          </small>
          
      </div>
    {% endfor %}
  </div>
  {% else %}
    
    <p style="text-align:center;font-weight:bold;">There are no payingguest in the database. Try a different keyword.  <a class="retry" href="{% url 'payingguest:all' %}">
    
    <i class="fa fa-undo" style="color:black;">Retry</i></a></p>
    
  {% endif %}
  </p>
  </div>
<!--{% if user.is_authenticated %}
<a style="font-weight: bold;font-size: 150%;" href="{% url 'logout' %}?next={% url 'payingguest:all' %}">Logout</a>
{% else %}
<a style="font-weight: bold;font-size: 150%;" href="{% url 'login' %}?next={% url 'payingguest:all' %}">Login</a>
{% endif %}-->
<script>
function favPost(url, payingguest_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+payingguest_id).toggle();
        $("#favorite_star_"+payingguest_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>

{% endblock %}